// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACNhaKyFMJ3pGNFFLC3wm7t6uZU3Va04I',
    appId: '1:1008380081377:web:526425268b6c3a5bedf3a0',
    messagingSenderId: '1008380081377',
    projectId: 'tago-ec338',
    authDomain: 'tago-ec338.firebaseapp.com',
    databaseURL: 'https://tago-ec338-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tago-ec338.firebasestorage.app',
    measurementId: 'G-R6MBGS6PL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB80tSTRXywKNHjgResqmKf8skCGbO7SJA',
    appId: '1:1008380081377:android:4884c86665a9645fedf3a0',
    messagingSenderId: '1008380081377',
    projectId: 'tago-ec338',
    databaseURL: 'https://tago-ec338-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tago-ec338.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWgTfJP-YzG_ZYd8jpPQGe_K2d8EUpzD4',
    appId: '1:1008380081377:ios:b28fd1b08b68784fedf3a0',
    messagingSenderId: '1008380081377',
    projectId: 'tago-ec338',
    databaseURL: 'https://tago-ec338-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tago-ec338.firebasestorage.app',
    iosBundleId: 'com.example.tfg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWgTfJP-YzG_ZYd8jpPQGe_K2d8EUpzD4',
    appId: '1:1008380081377:ios:b28fd1b08b68784fedf3a0',
    messagingSenderId: '1008380081377',
    projectId: 'tago-ec338',
    databaseURL: 'https://tago-ec338-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tago-ec338.firebasestorage.app',
    iosBundleId: 'com.example.tfg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACNhaKyFMJ3pGNFFLC3wm7t6uZU3Va04I',
    appId: '1:1008380081377:web:26c7f633481c620aedf3a0',
    messagingSenderId: '1008380081377',
    projectId: 'tago-ec338',
    authDomain: 'tago-ec338.firebaseapp.com',
    databaseURL: 'https://tago-ec338-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tago-ec338.firebasestorage.app',
    measurementId: 'G-8F2PHXQ3P7',
  );

}